@node sshd_config-example, sshd_config_example 2, ssh-config-example, Top
@chapter sshd_config-example
@display
#sshd_config,v 1.101 2017/03/14 07:19:07 djm Exp $
# Это общесистемный файл конфигурации сервера sshd. Смотрите sshd_config(5) для
#получения дополнительной информации.

# Этот sshd был скомпилирован с PATH=/usr/bin:/bin:/usr/sbin:/sbin

# Стратегия, используемая для параметров в sshd_config по умолчанию, поставляемом
# с OpenSSH, заключается в том, чтобы по возможности указывать параметры со значениями
# по умолчанию, но оставлять их в комментариях. Некомментированные параметры
# переопределяют значение по умолчанию.

#Port 22
#AddressFamily any
#ListenAddress 0.0.0.0
#ListenAddress ::

#HostKey /etc/ssh/ssh_host_rsa_key
#HostKey /etc/ssh/ssh_host_ecdsa_key
#HostKey /etc/ssh/ssh_host_ed25519_key

# Ciphers and keying
#RekeyLimit default none

# Logging
#SyslogFacility AUTH
#LogLevel INFO

# Authentication:

#LoginGraceTime 2m
#PermitRootLogin prohibit-password
PermitRootLogin yes
#StrictModes yes
#MaxAuthTries 6
#MaxSessions 10

#PubkeyAuthentication yes

# Ожидайте, что .ssh/authorized_keys2 будет игнорироваться по умолчанию в будущем.
#AuthorizedKeysFile	.ssh/authorized_keys .ssh/authorized_keys2

#AuthorizedPrincipalsFile none

#AuthorizedKeysCommand none
#AuthorizedKeysCommandUser nobody

# Для этого вам также понадобятся ключи хоста в /etc/ssh/ssh_known_hosts
#HostbasedAuthentication no
# Измените на да, если вы не доверяете ~/.ssh/known_hosts 
# HostbasedAuthentication
#IgnoreUserKnownHosts no
# Не читайте файлы пользователя ~/.rhosts и ~/.shosts
#IgnoreRhosts yes

# Чтобы отключить туннельные пароли в виде открытого текста, измените на 'no'здесь!
#PasswordAuthentication yes
#PermitEmptyPasswords no

# Измените на yes, чтобы включить пароли запроса-ответа (остерегайтесь проблем с
#некоторыми модулями и потоками PAM)
ChallengeResponseAuthentication no

# Kerberos опции
#KerberosAuthentication no
#KerberosOrLocalPasswd yes
#KerberosTicketCleanup yes
#KerberosGetAFSToken no

# GSSAPI options
#GSSAPIAuthentication no
#GSSAPICleanupCredentials yes
#GSSAPIStrictAcceptorCheck yes
#GSSAPIKeyExchange no

# Установите для этого параметра значение 'yes', чтобы включить проверку
# подлинности PAM, обработку учетной записи и обработку сеанса. Если это
# включено, аутентификация PAM будет разрешена через ChallengeResponseAuthentication
# и PasswordAuthentication. В зависимости от конфигурации PAM аутентификация PAM
# через ChallengeResponseAuthentication может обойти настройку
# "PermitRootLogin without-password". Если вы просто хотите, чтобы проверки учетных
# записей и сеансов PAM выполнялись без аутентификации PAM, включите эту функцию, но
# установите для PasswordAuthentication и ChallengeResponseAuthentication
# значение 'no'.
UsePAM yes

#AllowAgentForwarding yes
#AllowTcpForwarding yes
#GatewayPorts no
X11Forwarding yes
#X11DisplayOffset 10
#X11UseLocalhost yes
#PermitTTY yes
PrintMotd no
#PrintLastLog yes
#TCPKeepAlive yes
#UseLogin no
#PermitUserEnvironment no
#Compression delayed
#ClientAliveInterval 0
#ClientAliveCountMax 3
#UseDNS no
#PidFile /var/run/sshd.pid
#MaxStartups 10:30:100
#PermitTunnel no
#ChrootDirectory none
#VersionAddendum none

# отключение баннера по умолчанию
#Banner none

# Разрешить клиенту передавать переменные окружения локали
AcceptEnv LANG LC_*

# переопределить по умолчанию без подсистем
Subsystem	sftp	/usr/lib/openssh/sftp-server

# Пример переопределения настроек для каждого пользователя
# Match User anoncvs
#	X11Forwarding no
#	AllowTcpForwarding no
#	PermitTTY no
#	ForceCommand cvs server
@end display
